name: Nuclei - DAST Scan

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Nuclei - DAST Scan 2
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:5050
    
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif

